force-app/main/default/objects/PricebookEntry/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <label>Available Quantity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <label>Available Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Image__c.field-meta.xml
<CustomField>
    <fullName>Product_Image__c</fullName>
    <formula>IMAGE( DisplayUrl , &quot;Text Name of Image&quot;,36,36)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductService.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-24-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class ProductService {
    @AuraEnabled(cacheable=true)
    public static List<PricebookEntry> getProducts(String searchKey) {
        string value='%Watches%';
        String query = 'Select PriceBook2.Name,Product2.DisplayUrl,Product2.ProductCode, Product2Id,Pricebook2Id, Product2.Product_Image__c ,Product2.Available_Quantity__c, Product2.Name, UnitPrice From PricebookEntry WHERE PriceBook2.Name LIKE :value ' ;
        system.debug('query---'+query);
        if ( searchKey != null && searchKey != '' ) {
        String key = '%' + searchKey + '%';
        query += ' AND Product2.Name LIKE :key';
        }
        return Database.query( query );
}
}