force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{0000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Link_File__c.field-meta.xml
<CustomField>
    <fullName>Link_File__c</fullName>
    <label>Link / File</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Link</fullName>
            </value>
            <value>
                <fullName>File</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestUtility.cls
/**
* @description       : 
* @author            : RISHAB GOYAL
* @group             : 
* @last modified on  : 02-02-2021
* @last modified by  : RISHAB GOYAL
* Modifications Log 
* Ver   Date         Author         Modification
* 1.0   02-02-2021   RISHAB GOYAL   Initial Version
**/
public class TestUtility {
    
    public static ContentDocumentLink createContentVersion(String title, Id LinkedEntityId){
        
        ContentVersion cv = new ContentVersion();
        cv.title = title;      
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;         
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=LinkedEntityId;
        contentlink.ShareType= 'I';
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;
        return contentlink;
    }    
    
    public static Document__c createDocument(Id opportunityId, String fileType){
        Document__c testDoc = new Document__c(Opportunity__c= opportunityId, Link_File__c = fileType);
        insert testDoc;
        return testDoc;
    }
    
    public static Account createCustomerAccount(string accountName){
        Account acc =  new Account(name = accountName);
        acc.BillingCountry = 'India';
        acc.Website = 'https://www.test.com';
        insert acc;
        return acc;
    }
    
    public static List<Opportunity> createOpportunity(Id accountId, string Name, Integer noOfOpportunities){
        List<Opportunity> oppoList = new List<Opportunity>();
        
        for(Integer i=0; i < noOfOpportunities; i++ )
        {
            Opportunity oppo = new Opportunity();
            oppo.AccountId = accountId;
            oppo.Name = Name + i;
            oppo.StageName = 'Qualification';
            oppo.CloseDate = System.today().addMonths(2);
            oppo.Pricebook2Id = Test.getStandardPricebookId();
            oppoList.add(oppo);
        }
        
        insert oppoList;
        return oppoList;
    }
    public static void createCase(Id AccountId){
        Case testCase  = new Case(AccountId=AccountId );
        insert testCase;
    }
}