force-app/main/default/objects/Timeline__c/Timeline__c.object-meta.xml
<CustomObject>
    <label>Timeline</label>
    <nameField>
        <displayFormat>TIME-{0000}</displayFormat>
        <label>Timeline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline__c/fields/Changed_By__c.field-meta.xml
<CustomField>
    <fullName>Changed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Changed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timelines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timeline__c/fields/Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Changed_Date__c</fullName>
    <label>Changed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timeline__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Timelines</relationshipLabel>
    <relationshipName>Timelines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timeline__c/fields/Parent_Type__c.field-meta.xml
<CustomField>
    <fullName>Parent_Type__c</fullName>
    <label>Parent Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHelper.cls
public class OpportunityTriggerHelper {
    
    public static void createTimeLineOnOpportunityCreation(Map<Id, Opportunity> newOpportunityMap, Map<Id, TimeLine__c> timeLineMap, Map<Id, Opportunity> oldOpportunityMap){
        List<Timeline__c> timelist = new List<Timeline__c>();
        for(Opportunity tempOppo: newOpportunityMap.values()){
            
            String newValue = tempOppo.StageName;
            String oldValue = trigger.isInsert ? null : oldOpportunityMap.get(tempOppo.Id).StageName;
            
            Timeline__c tempTimeLine = new Timeline__c();
            tempTimeLine.Opportunity__c = tempOppo.Id;
            tempTimeLine.Changed_By__c = Userinfo.getUserId();
            tempTimeLine.Changed_Date__c = tempOppo.LastModifiedDate;
            tempTimeLine.New_Value__c = newValue;
            tempTimeLine.Parent_Type__c = 'Opportunity';
            tempTimeLine.Old_Value__c = oldValue;
            tempTimeLine.Last_Modified_Date__c = trigger.isInsert ? System.now() : timeLineMap.get(tempOppo.Id).Changed_Date__c;
            
            timelist.add(tempTimeLine);
        }
        if(timelist.size() > 0){
            insert timelist;
        }
    }
    
    public static void manageTimeline(Map<Id, Opportunity> newOpportunityMap, Map<Id, Opportunity> oldOpportunityMap){
        List<Timeline__c> timelist = new List<Timeline__c>();
        List<Opportunity> insertOpportunityList = new List<Opportunity>();
        Map<Id, Opportunity> updateOpportunityMap = new Map<Id, Opportunity>();
        Boolean isStageUpdate = false;
        Set<Id> stageUpdateIds = new Set<Id>(); 
        
        if(trigger.isInsert){
            createTimeLineOnOpportunityCreation(newOpportunityMap, null, null);
            return;
        } else {
            for(Opportunity tempOppo : newOpportunityMap.values()){
                if (trigger.isUpdate && tempOppo.StageName != oldOpportunityMap.get(tempOppo.Id).StageName){
                    updateOpportunityMap.put(tempOppo.Id, tempOppo);
                    stageUpdateIds.add(tempOppo.Id);       
                }
            }
        }
        Map<Id, Timeline__c>  timeLineMap = new Map<Id, Timeline__c>();
        
        for(Timeline__c temp : [SELECT Id, Changed_Date__c, Opportunity__c FROM Timeline__c Where Opportunity__c IN :stageUpdateIds order by createdDate desc]){
            if(!timeLineMap.containsKey(temp.Opportunity__c)){
                timeLineMap.put(temp.Opportunity__c, temp);
            }
        }
        createTimeLineOnOpportunityCreation(updateOpportunityMap, timeLineMap, oldOpportunityMap);  
    }
}