force-app/main/default/objects/Timeline__c/Timeline__c.object-meta.xml
<CustomObject>
    <label>Timeline</label>
    <nameField>
        <displayFormat>TIME-{0000}</displayFormat>
        <label>Timeline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Timeline</relationshipLabel>
    <relationshipName>Timeline</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTriggerTest.cls
@isTest
public class LeadTriggerTest {
    
    @testSetup
    public static void testSetupMethod(){
        Lead objLead = new Lead( FirstName = 'Test', LastName = 'Sample', Company = 'Testing Sample Co' );  
        insert objLead; 
    }
    
    @isTest
    public static void testforLeadInsert(){
        lead testlead = [SELECT Id, Name FROM Lead LIMIT 1];
        List<Timeline__c> timeLineList = [SELECT Id FROM Timeline__c WHERE lead__c = :testlead.Id];
        System.assertEquals(1, timeLineList.size(), 'Timeline Exists');
    }    
    
    @isTest
    public static void testforLeadUpdate(){
        lead testlead = [SELECT Id, Name FROM Lead LIMIT 1];
       	testlead.Status = 'Working - Contacted';
        update testlead;
        
        List<Timeline__c> timeLineList = [SELECT Id FROM Timeline__c WHERE lead__c = :testlead.Id];
        System.assertEquals(2, timeLineList.size(), 'Timeline Exists');
    }
}