force-app/main/default/objects/Timeline__c/Timeline__c.object-meta.xml
<CustomObject>
    <label>Timeline</label>
    <nameField>
        <displayFormat>TIME-{0000}</displayFormat>
        <label>Timeline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Timeline</relationshipLabel>
    <relationshipName>Timeline</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseTriggerTest.cls
@isTest
public class CaseTriggerTest {
    @testSetup
    public static void testSetupMethod(){
        Account testAccount = TestUtility.createCustomerAccount('TestAccount');
        TestUtility.createCase(testAccount.Id); 
    }
    
    @isTest
    public static void testforLeadInsert(){
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        List<Timeline__c> timeLineList = [SELECT Id FROM Timeline__c WHERE Case__c = :testCase.Id];
        System.assertEquals(1, timeLineList.size(), 'Timeline Exists');
    }    
    
    @isTest
    public static void testforLeadUpdate(){
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        testCase.Status = 'Working';
        update testCase;
        
        List<Timeline__c> timeLineList = [SELECT Id FROM Timeline__c WHERE Case__c = :testCase.Id];
        System.assertEquals(2, timeLineList.size(), 'Timeline Exists');
    }
}