force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flat__c/Flat__c.object-meta.xml
<CustomObject>
    <label>Flat</label>
    <nameField>
        <displayFormat>FT-{0000}</displayFormat>
        <label>Flat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flat__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Flats</relationshipLabel>
    <relationshipName>Flats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BuildingController.cls
/**
 * @description       : 
 * @author            : navin.patil@rupeek.com
 * @group             : 
 * @last modified on  : 06-10-2022
 * @last modified by  : navin.patil@rupeek.com
 //test comment added navin
**/

public with sharing class BuildingController {
    
    @AuraEnabled
    public static Building__c insertBuilding(Building__c buildingObj){
        try {
            System.debug(buildingObj);
            insert buildingObj;
            return buildingObj;
        } catch (Exception exp) {
            throw new AuraHandledException(exp.getMessage());
        }
    }
    
    @AuraEnabled
    public static Flat__c insertFlat(Flat__c flatObj){
        try {
            System.debug(flatObj);
            insert flatObj;
            return flatObj;
        } catch (Exception exp) {
            System.debug(exp);
            throw new AuraHandledException(exp.getMessage());
        }
    }


}